Repository bucketlist-3216/bucketlist, pull requests merged in 2019-11, with the labels that each got.

#152 Add group features
  assets/fonts/CeraPro-Light.ttf
  package-lock.json
  src/client/api/trip-friend.js
  src/client/components/AddFriendModal/AddFriendModal.jsx
  src/client/components/AddFriendModal/index.js
  src/client/components/GroupSettings/GroupSettings.jsx
  src/client/components/GroupSettings/index.js
  src/client/components/Spinner/Spinner.jsx
  src/client/components/Spinner/index.js
  src/client/components/TripDetails/TripDetails.jsx
  src/client/components/TripDetails/index.js
  src/client/components/TripFriend/TripFriend.jsx
  src/client/components/TripFriend/index.js
  src/client/constants/apis.js
  src/client/pages/PlaceList/PlaceList.jsx
  src/client/pages/TripsPage/TripsPage.jsx
  src/client/styles/abstracts/_fonts.scss
  src/client/styles/buttons/__buttons-dir.scss
  src/client/styles/buttons/_add-button.scss
  src/client/styles/buttons/_home-button.scss
  src/client/styles/buttons/_icon-button.scss
  src/client/styles/components/__components-dir.scss
  src/client/styles/components/_add-friend-modal.scss
  src/client/styles/components/_group-settings.scss
  src/client/styles/components/_trip-details.scss
  src/client/styles/components/_trip-friend.scss
  src/client/styles/pages/_list-page.scss
  src/client/styles/pages/_trips-page.scss
  src/server/api/handlers/trip-friend.js
  src/server/api/query-models/trip-friend-query-model.js
  src/server/api/query-models/user-query-model.js
  src/server/api/routes/trip.js
Labels: ready-to-merge, request-review

#172 Swipe Changes (before peer review session)
  assets/common/user-icon.png
  src/client/buttons/HomeButton/HomeButton.jsx
  src/client/buttons/HomeButton/index.js
  src/client/buttons/IconButton.jsx
  src/client/buttons/ProfileButton/ProfileButton.jsx
  src/client/buttons/ProfileButton/index.js
  src/client/components/AppBarTop/PlaceListTopBar.jsx
  src/client/components/SideDrawer/SideDrawer.jsx
  src/client/components/Swipe/Swipe.jsx
  src/client/components/Swipe/SwipeCard/SwipeCard.jsx
  src/client/styles/buttons/__buttons-dir.scss
  src/client/styles/buttons/_home-button.scss
  src/client/styles/buttons/_icon-button.scss
  src/client/styles/buttons/_profile-button.scss
  src/client/styles/components/_side-drawer.scss
  src/client/styles/components/_swipe.scss
Labels: ready-to-merge

#173 Add new tutorials
  src/client/components/Tutorial/Tutorial.jsx
  src/client/styles/pages/_tutorial-page.scss
Labels: ready-to-merge, request-review

#179 Swipe List Notification
  src/client/components/SideDrawer/SideDrawer.jsx
  src/client/components/Swipe/Swipe.jsx
  src/client/constants/apis.js
  src/client/constants/paths.js
  src/client/styles/components/_swipe.scss
Labels: ready-to-merge

#180 fix empty group bug
  src/client/components/TripDetails/TripDetails.jsx
  src/client/styles/components/_trip-details.scss
Labels: ready-to-merge

#174 Show only places with atleast 1 like
  src/server/api/query-models/vote-query-model.js
Labels: ready-to-merge, request-review

#176 Make Create Trip page
  src/client/BucketList.jsx
  src/client/api/login.js
  src/client/api/trip-friend.js
  src/client/api/trip.js
  src/client/api/user.js
  src/client/buttons/ProfileButton/ProfileButton.jsx
  src/client/components/AppBarTop/PlaceListTopBar.jsx
  src/client/components/CitySelect/CityCard/CityCard.jsx
  src/client/components/CitySelect/CityCard/index.js
  src/client/components/CitySelect/CitySelect.jsx
  src/client/components/CitySelect/index.js
  src/client/components/ProfileBanner/ProfileBanner.jsx
  src/client/components/ProfileBanner/index.js
  src/client/components/SingleSignOnButton/SingleSignOnButton.jsx
  src/client/components/Swipe/Swipe.jsx
  src/client/components/Trip/Trip.jsx
  src/client/components/TripDetails/TripDetails.jsx
  src/client/components/TripInfo/TripInfo.jsx
  src/client/components/TripInfo/index.js
  src/client/components/Tutorial/Tutorial.jsx
  src/client/components/TutorialPopup/TutorialPopup.jsx
  src/client/constants/apis.js
  src/client/constants/error-messages.json
  src/client/constants/paths.js
  src/client/pages/CitySelect/CitySelect.jsx
  src/client/pages/CreateTrip/CreateTrip.jsx
  src/client/pages/CreateTrip/index.js
  src/client/pages/Login/Login.jsx
  src/client/pages/PlaceList/PlaceList.jsx
  src/client/pages/ProfilePage/ProfilePage.jsx
  src/client/pages/TripsPage/TripsPage.jsx
  src/client/styles/buttons/_profile-button.scss
  src/client/styles/components/__components-dir.scss
  src/client/styles/components/_city-select.scss
  src/client/styles/components/_trip-details.scss
  src/client/styles/components/_trip-info.scss
  src/client/styles/components/_trip.scss
  src/client/styles/pages/__pages-dir.scss
  src/client/styles/pages/_create-trip.scss
  src/client/styles/pages/_list-page.scss
  src/server/api/query-models/trip-friend-query-model.js
  src/server/api/query-models/trip-query-model.js
  src/server/api/routes/login.js
  src/server/api/routes/trip.js
Labels: ready-to-merge, request-review

#205 show trip members' photos in profile page
  src/client/buttons/IconButton.jsx
  src/client/components/Trip/Trip.jsx
  src/client/constants/apis.js
  src/client/styles/buttons/_profile-button.scss
  src/client/styles/components/_trip.scss
Labels: ready-to-merge, reviewed

#199 fix bugs on group page and handle error better with toast
  assets/brand/brand-logo.png
  assets/demo/GardensByTheBay.jpg
  assets/demo/LauPaSatSatay.jpg
  assets/demo/MarinaBaySands.jpg
  assets/demo/SingaporeFlyer.jpg
  assets/demo/YaKunKayaToast.jpg
  assets/tutorial/1.jpg
  assets/tutorial/2.jpg
  assets/tutorial/3.jpg
  package-lock.json
  package.json
  src/client/BucketList.jsx
  src/client/api/login.js
  src/client/api/trip-friend.js
  src/client/api/trip.js
  src/client/api/user.js
  src/client/components/AddFriendModal/AddFriendModal.jsx
  src/client/components/GroupSettings/GroupSettings.jsx
  src/client/components/SingleSignOnButton/SingleSignOnButton.jsx
  src/client/components/Swipe/Swipe.jsx
  src/client/components/TripFriend/TripFriend.jsx
  src/client/pages/PlaceList/PlaceList.jsx
  src/client/pages/ProfilePage/ProfilePage.jsx
  src/client/pages/TripsPage/TripsPage.jsx
  src/client/styles/styles.scss
  src/client_old/components/AddFriendModal/AddFriendModal.jsx
  src/client_old/components/Create/Create.jsx
  src/client_old/components/Login/Login.jsx
  src/client_old/components/Swipe/Swipe.jsx
  src/client_old/components/Swipe/SwipeCard/SwipeCard.jsx
  src/client_old/pages/ListPage/ListPage.jsx
  src/client_old/pages/TripsPage/TripsPage.jsx
Labels: reviewed

#201 fix bugs in swipe page and add log in button for guest user in menu drawer
  src/client/buttons/IconButton.jsx
  src/client/buttons/ProfileButton/ProfileButton.jsx
  src/client/components/AppBarTop/PlaceListTopBar.jsx
  src/client/components/SideDrawer/SideDrawer.jsx
  src/client/components/Swipe/Swipe.jsx
  src/client/constants/apis.js
  src/client/pages/PlaceList/PlaceList.jsx
  src/client/styles/buttons/_icon-button.scss
  src/client/styles/components/_profile-banner.scss
  src/client/styles/components/_side-drawer.scss
  src/client/styles/components/_swipe.scss
  src/client/styles/pages/_profile-page.scss
  src/client/styles/pages/_trips-page.scss
Labels: request-review

#203 add more space between username and name
  src/client/components/SideDrawer/SideDrawer.jsx
  src/client/styles/components/_side-drawer.scss
Labels: ready-to-merge

#208 make manage trip page responsive
  src/client/components/TripInfo/TripInfo.jsx
  src/client/constants/apis.js
  src/client/pages/PlaceList/PlaceList.jsx
  src/client/styles/components/_trip-info.scss
  src/client/styles/pages/_list-page.scss
  src/client/styles/pages/_profile-page.scss
Labels: request-review

#202 fix some desktop scaling issues
  src/client/components/GroupSettings/GroupSettings.jsx
  src/client/pages/Login/Login.jsx
  src/client/pages/PlaceList/PlaceList.jsx
  src/client/styles/components/_group-settings.scss
  src/client/styles/components/_side-drawer.scss
  src/client/styles/components/_swipe.scss
  src/client/styles/pages/_app-home.scss
  src/client/styles/pages/_list-page.scss
Labels: request-review

#207 fix edit profile page ui
  assets/common/default-cover.jpg
  assets/common/default-landscape.jpg
  src/client/components/ProfileBanner/ProfileBanner.jsx
  src/client/pages/ProfilePage/ProfilePage.jsx
  src/client/styles/pages/_profile-page.scss
Labels: request-review
